#ifndef SEVEN_SEGMENTS_INTERFACE_H
#define SEVEN_SEGMENTS_INTERFACE_H

#include "../../charUtils/include/charUtils.h"

#define SEVEN_SEGMENTS_INTERFACE_DEBUG 0

#define SEVEN_SEGMENTS_INTERFACE_HEADER_NAME "SEVEN SEGMENTS"

#define SEVEN_SEGMENTS_INTERFACE_HEADER "se"

#define SEVEN_SEGMENTS_INTERFACE_HEADER_SIZE 2
#define SEVEN_SEGMENTS_INTERFACE_COMMAND_SIZE 1

#define WRITE_ONE_SEVEN_SEGMENTS_HEADER "1"
#define WRITE_TWO_SEVEN_SEGMENTS_HEADER "2"
#define WRITE_THREE_SEVEN_SEGMENTS_HEADER "3"
#define WRITE_FOR_SEVEN_SEGMENTS_HEADER "4"

#define SEVEN_SEGMENTS_HELP_HEADER "h"

void sevenSegmentsInterface(char rxBuffer[50]);

#endif